### ISSUE TITLE
Twitter Timeline embed is not working. Any ideas why?

### ISSUE THREAD

**Issue by vishishttiwari** [saurabhnemade/react-twitter-embed#116]
I am not seeing any error in console as well. 
![image](https://user-images.githubusercontent.com/31442258/185577135-048672b7-c6c6-41f5-b724-ac7db577baa6.png)

**Comment by Royal-lobster** [comment]
it seems to be a bug. profile urls are not working
- https://saurabhnemade.github.io/react-twitter-embed/?path=/story/twitter-timeline-embed--timeline-url-with-profile-url
<img width="1423" alt="CleanShot 2022-08-21 at 17 12 18@2x" src="https://user-images.githubusercontent.com/52039218/185789294-c431415b-2600-44ad-b18e-dcd3f6e7f4ac.png">

**Comment by gsabanci** [comment]
I also have the same problem. Especially on timeline which sourcetype is 'profile' or 'list'. Twitter made an update 3-4 days ago, but I couldn't find any explanatory documentation. Could you please inform me if you solve this problem?

**Comment by Claytonn** [comment]
Also having this issue with profile timelines, it doesn't seem to be specific to this library but a global embed change by Twitter.

**Comment by leifdejong** [comment]
We have also been having problems with the timeline for the last 3-5 days. Seems like the options (e.g. No header, no background, no scrolling, etc) are not being respected:

<img width="519" alt="Screen Shot 2022-08-22 at 3 09 12 PM" src="https://user-images.githubusercontent.com/1885446/186009795-2ba72128-c87f-4e91-bccb-2d2165f9b58a.png">

**Comment by saurabhnemade** [comment]
Seems like update in twitter lib. will try to fix it sooner.

**Comment by JGabT** [comment]
any updates on this? thanks in advance :)

**Comment by jarodtaylor** [comment]
Same issue. The options look to be the same on Twitter's end and if you use the classic DOM implementation the options work, so it's definitely something on the lib side.

**Comment by potapovnikita** [comment]
when will you fix it? =(

**Comment by Claytonn** [comment]
> Same issue. The options look to be the same on Twitter's end and if you use the classic DOM implementation the options work, so it's definitely something on the lib side.

Anyone else also not seeing any embed options other than height/width working? Seems like transparency and other options are broke in both this implementation and the regular embed code.

**Comment by leifdejong** [comment]
@saurabhnemade it appears from our end that the issue has been resolved. Possibly a change on twitter's end? Just wanted to inform you of our finding.

**Comment by ddcrobert** [comment]
I encountered the same issue with the vertical line.
I think the issue is around the intermediate div which contains the actual .twitter-timeline.
Thus, I end up working around the issue with some css:

`
div:has(> .twitter-timeline) {
  width: 100%;
}
`

**Comment by vincemurphy** [comment]
I had same issue and added a width in the options and that fixed it although I still have issues with it being very slow to load and not polling twitter for most recent tweets to render

**Comment by JPscript** [comment]
This maybe can help, I change my code using the one provided here in [Twitter](https://publish.twitter.com/#) and just change the script tag for a component script tag. [<ScriptTag>](https://www.npmjs.com/package/react-script-tag), it's an option if you still have problems. Also try to help solve issues to the developer.
